# Generated by Django 4.2.6 on 2023-10-07 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
