# Generated by Django 4.2.6 on 2023-10-07 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_tracker', '0002_rename_tags_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='file',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='document_tracker.file'),
            preserve_default=False,
        ),
    ]
