# Generated by Django 4.2.6 on 2023-10-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tracker', '0004_remove_tag_file_filetag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='file',
            name='last_modified_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date last modified'),
        ),
    ]
