# Generated by Django 4.2.6 on 2023-10-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_tracker', '0005_alter_file_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
