# Generated by Django 4.2.6 on 2023-10-14 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("document_tracker", "0006_remove_tag_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="created_by",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="file_name",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="file",
            name="last_modified_by",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_edited_by",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="version_notes",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="file",
            name="version_number",
            field=models.IntegerField(default=0),
        ),
    ]
