# Generated by Django 4.2.6 on 2023-10-14 06:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("document_tracker", "0008_alter_file_file_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="file",
            name="last_modified_by",
        ),
    ]
