# Generated by Django 4.2.6 on 2023-10-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document_tracker", "0010_file_created_by_file_last_modified_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="latest",
            field=models.BooleanField(default=False),
        ),
    ]
