# Generated by Django 4.2.6 on 2023-10-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document_tracker", "0011_file_latest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="latest",
            field=models.BooleanField(default=True),
        ),
    ]
