# Generated by Django 4.2.7 on 2023-11-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_tracker', '0012_alter_file_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetag',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='document_tracker.file'),
        ),
    ]
