# Generated by Django 4.2.7 on 2023-11-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tracker', '0014_alter_file_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=100),
        ),
    ]
